### ISSUE TITLE
建议参考一下这个源码 

### ISSUE THREAD

**Issue by hijk1234** [ooclab/otunnel#11]
https://github.com/fatedier/frp

**Comment by gwind** [comment]
frp 是一个不错的项目，但我们参考源码的目标是什么呢？

otunnel 基于我们开发的 es , 原理上不同于 ngrok , frp 等项目：otunnel / es 不是为了代理目的而开发的。

es 的初衷是为了开发小水滴云计算项目-核心的网络部分。我们经历过：
1. ZeroMQ -> 私有MQ -> es (无MQ)
2. Python -> Golang

**Comment by gwind** [comment]
https://github.com/ooclab/es

**Comment by gwind** [comment]
当初从 MQ 转到 TCP PORT MAP, 参考过 https://github.com/getqujing/qtunnel
只是 qtunnel 是单向的，我们认为 TCP 连接 (Link) 建立后，如果运行 tunnel, channel 应该是双向（方向无关），因此与 qtunnel 有很大的区别。

欢迎补充 :smile:
