### ISSUE TITLE
time="01/18 14:28:53" level=warning msg="can not find channel 3:3"是什么问题？

### ISSUE THREAD

**Issue by XiaolinYi** [ooclab/otunnel#19]
反向代理时，目标客户端提示如下：
time="01/18 14:28:53" level=warning msg="can not find channel 3:3"

**Comment by gwind** [comment]
这个问题可能是：一端的某个 TCP 链接（一个 channel）断开了，而另外一端的数据后到。而 otunnel 每个数据包中的ID，会最终查询到对应的 channel ID，这样才能将数据包准确转发到该 channel 。因此这种情况下的 channel 已经断开，就表现为上面的警告。这个大部分情况下都属于正常情况。

如果要更友好地显示该信息，otunnel 需要如下改进：
1. 添加锁, 如果channel (TCP)断开, 加锁记录原因（正常、异常）
2. 出现找不到 channel ID 情况，加锁查询是否有记录。根据记录原因，显示断开原因。
