### ISSUE TITLE
X11VNC

### ISSUE THREAD

**Issue by gvsurenderreddy** [ooclab/otunnel#20]
Hello sir 
I'm trying to use otunnel on Nated X11VNCserver to Remote Public VPS server then to VNCclient but i have only handshaking with remote host then nothing happens 

tunnel 3 L::7900 -> R:127.0.0.1:7900 accept new client 49.207.4.103:49883
DEBU[04/27 19:09:58] listenTCP: OPEN channel [TCP Channel] 3-5: L(159.69.127.85:7900), R(49.207.4.103:49883) success
DEBU[04/27 19:10:09] ping success                                  from=link id=0 rtt=258.746102ms
DEBU[04/27 19:11:10] ping success                                  from=link id=0 rtt=275.702157ms
DEBU[04/27 19:11:40] ping success                                  from=link id=0 rtt=586.867942ms
DEBU[04/27 19:12:11] ping success                                  from=link id=0 rtt=301.321794ms

**Comment by gwind** [comment]
Hi, @gvsurenderreddy 

Can you give me the the details of two (`otunnel listen` and `otunnel connect`) commands ?

For example :

If host A have a public ip (or any ip your vnc client can connect to it) , run :

```
./otunnel listen :10000 -d -s secret
```

The go to host B (can connect the vnc server) and run:

```
./otunnel connect ${HOST_A_IP}:10000 -d -s secret -t r:${VNC_HOST_IP}:${VNC_HOST_PORT}::${VNC_REMOTE_PORT}
```

The your vnc client should connect to `${HOST_A_IP}:${VNC_REMOTE_PORT}`

**Comment by gvsurenderreddy** [comment]
otunnel listen :10000 -d -s secret
INFO[04/29 02:17:33] start (aes) server on :10000 success
DEBU[04/29 02:17:34] accept new client                             LocalAddr="159.69.1.80:10000" RemoteAddr="103.255.5.27:21017"
DEBU[04/29 02:17:34] handle auth, got request: map[action:new]
DEBU[04/29 02:17:34] prepare to create new link with config &link.LinkConfig{IsServerSide:true, KeepaliveInterval:30000000000, ConnectionWriteTimeout:0}
DEBU[04/29 02:17:34] create link success                           from=link id=0
DEBU[04/29 02:17:34] start underlying send                         from=link id=0
DEBU[04/29 02:17:34] start keepalive                               from=link id=0 interval=30s max_timeout=10s
DEBU[04/29 02:17:34] start underlying recv                         from=link id=0
DEBU[04/29 02:17:34] got config for tunnel create: tcp: L(:7900) -> R(127.0.0.1:7900)
DEBU[04/29 02:17:34] prepare to create a tunnel with config tcp: L(:7900) -> R(127.0.0.1:7900)
DEBU[04/29 02:17:34] start listen tunnel 3 L::7900 -> R:127.0.0.1:7900 success
DEBU[04/29 02:17:34] create forward tunnel: 3 L::7900 -> R:127.0.0.1:7900
DEBU[04/29 02:18:04] ping success                                  from=link id=0 rtt=164.828673ms
DEBU[04/29 02:18:34] ping success                                  from=link id=0 rtt=163.952694ms
DEBU[04/29 02:18:55] tunnel 3 L::7900 -> R:127.0.0.1:7900 accept new client 49.207.4.103:49336
DEBU[04/29 02:18:55] listenTCP: OPEN channel [TCP Channel] 3-2: L(159.69.1.80:7900), R(49.207.4.103:49336) success


client side 

otunnel connect 159.69.1.80:10000 -d -s secret -t r:127.0.0.1:7900::7900
DEBU[04/29 03:07:14] connect to 159.69.1.80:10000 success         
DEBU[04/29 03:07:14] prepare to create new link with config &link.LinkConfig{IsServerSide:false, KeepaliveInterval:30000000000, ConnectionWriteTimeout:0} 
DEBU[04/29 03:07:14] create link success                           from=link id=0
DEBU[04/29 03:07:14] start underlying send                         from=link id=0
DEBU[04/29 03:07:14] start underlying recv                         from=link id=0
DEBU[04/29 03:07:14] start keepalive                               from=link id=0 interval=30s max_timeout=10s
DEBU[04/29 03:07:14] open tunnel in the remote endpoint success    config="tcp: L(127.0.0.1:7900) <- R(:7900)"
DEBU[04/29 03:07:14] prepare to create a tunnel with config tcp: L(127.0.0.1:7900) <- R(:7900) 
DEBU[04/29 03:07:14] create forward tunnel: 3 L:127.0.0.1:7900 <- R::7900 
DEBU[04/29 03:07:14] open tunnel in the local side success         tunnel="3 L:127.0.0.1:7900 <- R::7900"

but for me its just handshaking with remote host and nothing happens
<img width="562" alt="Screenshot 2020-04-29 at 5 51 54 AM" src="https://user-images.githubusercontent.com/14979881/80550368-8a57a980-89dd-11ea-814d-1c3c295fdf3a.png">

**Comment by gvsurenderreddy** [comment]
I just tried other Tunnel service its working fine https://github.com/fatedier/frp
<img width="1140" alt="Screenshot 2020-04-29 at 9 17 40 AM" src="https://user-images.githubusercontent.com/14979881/80559202-6787be00-89fa-11ea-8131-d6bc0efa1b2f.png">

**Comment by gwind** [comment]
@gvsurenderreddy , 

Can you test a normal tcp port ( such as ssh ), instead of vnc server?
I'm not sure what's it.

btw, frp is a nice tool.
