### ISSUE TITLE
请教一下使用范围

### ISSUE THREAD

**Issue by xsjqqq123** [ooclab/otunnel#4]
问下，家用路由器是否可以使用？比如我家里路由器上连着一个树霉派，里边有个网站，是否能将它映射出来？流量怎么走,是否需要经过服务端？这个与ngrok这种反向代理的有区别吗？

**Comment by gwind** [comment]
**可以**

otunnel **不限制网络**（只要 client 可以连接到 server）、 **不限制平台** （只要 golang 可以编译的平台）

你这种情况，可以这样：

1. 外面有个阿里云主机(或其他有公网IP的机器)，运行 otunnel server 角色
2. 树莓派上运行 otunnel client 角色

ngrok 我没用过，otunnel 相对其他工具对比，目前来说，优点有：

1. **简单**

可能的缺点:

1. 我们没有提供默认的中央服务器，所以用户不能只启动一个 client 达到自动的映射需求。用户需要自己启动外网的 otunnel server 角色。

**Comment by chenhao890411** [comment]
INFO[06/09 09:23:11] start (aes) server on :10000 success
ERRO[06/09 09:23:27] Link.recv quit                                error=EOF from=link id=0
WARN[06/09 09:23:27] link is stopped already                       from=link id=0
WARN[06/09 09:23:27] client &es.SafeConn{BaseConn:es.BaseConn{conn:(*net.TCPConn)(0xc42000e050)}, cipher:(*ecrypt.Cipher)(0xc42000cca0)} is offline

请问怎么解决

**Comment by gwind** [comment]
这个应该是远程的 TCP 关闭了。然后 recv 协程退出。
这一处的逻辑不好处理，如果阅读源码，可以看下 es.Link

请问：你是使用标准的 otunnel 源码编译执行，还是修改了源码在测试？
