### ISSUE TITLE
(已解决)怎么没有mipsle32位架构的二进制程序?

### ISSUE THREAD

**Issue by idontlikeit** [ooclab/otunnel#8]
小白一个，不会编译，我想在路由器运行

**Comment by gwind** [comment]
我测试过树莓派(arm)，其他架构没有测试过，可能你需要搜下golang程序如何在指定平台编译。otunnel 是纯Golang实现的。

**Comment by idontlikeit** [comment]
golang 1.8版本已经支持交叉编译了,现在golang都已经更新到了1.9版本了. 希望作者能更新全平台的二进制程序.我超级喜欢这个程序,好用简单. 可惜自己没技术,要不然也可以贡献代码.

**Comment by gwind** [comment]
:smiley: 
1. golang 交叉编译比较简单，主要是确测试环境，不清楚编译后的有没有问题，因此没有编译mipsle32（确实有需求的，可以参考README，尝试编译一下）
2. 我们已经用上golang1.9, 测试过编译
3. 可以从 docker scratch image 创建自己的 golang 镜像，最小化
感谢使用！

**Comment by demostars** [comment]
@idontlikeit  嗨，您的路由器是Padavan之类的MT7620的机器么，二进制方便共享下么~~
![image](https://user-images.githubusercontent.com/20697190/31648722-e74b8168-b341-11e7-8faf-b7155154cabe.png)

**Comment by gwind** [comment]
@idontlikeit 方便的把你的硬件架构信息和编译参数写个 FAQ，方便其他小伙伴 :-)

**Comment by idontlikeit** [comment]
CPU是MT7260A, 架构是mipsle 32位, 没用啥参数,就是用默认的makefile或者用go build都行. 下面是我编译出来的二进制程序, 本人能运行成功
[mipsle32.zip](https://github.com/ooclab/otunnel/files/1393818/mipsle32.zip)

@demostars
