### ISSUE TITLE
我分别用make和go build编译后的大小不一样

### ISSUE THREAD

**Issue by idontlikeit** [ooclab/otunnel#9]
arm32
amr64
mipsle32
386
amd64

以上总共5个,我总共编译了十次,就是make和go build

为什么"同系统同cpu"用make和go build编译后大小不一样

我用make编译arm64/Linux大小是3.9M，但我用go build编译后的大小却是6.1M
怎么差距这么大.

全部都能运行,没发现有任何问题.

只是对这个问题觉得很好奇

**Comment by gwind** [comment]
`go build` 是默认的 golang 编译参数，`make` 用了 `-ldflags "-s"` 参数（作用是，去掉一些信息），因此会小一点。
make 可以查看 Makefile 文件
